### ISSUE TITLE
How to specify

### ISSUE THREAD

**Issue by acidpancake** [Alvarito050506/thetracker#1]
how do you specify a nickname to the localhost?

**Comment by Alvarito050506** [comment]
Hello @acidpancake! You need to pass one of the following GET arguments in the request:
+ **name**: the nickname of the user you want to track, or
+ **id**: the id of the user you want to track.

For an example: `http://localhost/?name=Alvarito050506`.

**Comment by Alvarito050506** [comment]
@acidpancake Aparently the BC protocal has changed and TheTracker doesn't work for now. I will update it soon.

**Comment by acidpancake** [comment]
Hey @Alvarito050506 thanks for your reply!

Every name is insert is offline. Maybe Check?

**Comment by Alvarito050506** [comment]
Hello @acidpancake! I'm working to fix this:

> @acidpancake Aparently the BC protocol has changed and TheTracker doesn't work for now. I will update it soon.

**Comment by Alvarito050506** [comment]
@acidpancake I've just updated the code, now it implements the new protocol, try to download and run it.

I will close this issue. If you have any problem please open another. And thanks for your contribution!
