### ISSUE TITLE
Migration from boxcritters.com to play.boxcritters.com

### ISSUE THREAD

**Issue by acidpancake** [Alvarito050506/thetracker#2]
RocketSnail Has Moved BC To play.boxcritters.com

Will that cause the bot to stop working?

And Rsnail added auto reconnect so.. yeah heads up.

 _annnnddd_ can you implement a auto reconnect feature for example if we lose internet, the bot will still try to connect instead of just closing?

Thanks For Reading This! _(or did you read it.....)_

TechnoByte

**Comment by Alvarito050506** [comment]
Hello @acidpancake! Thanks for opening this issue! It is really useful.

 + Yes, TheTracker will stop working for now. But don't worry, it only needs a quick fix.
 + I hope I can implement auto-reconnect, but I don't really know anything about how it is implemented in Box Critters, so it may take a while.

Just out of curiosity, for what are you using TheTracker?

**Comment by acidpancake** [comment]
Im using the tracker for a soon discord bot and for my alt to stay on all the time

**Comment by Alvarito050506** [comment]
Interesanting... I love to see that there is people using my software!

**Comment by acidpancake** [comment]
Yeah! If you dont mind can we talk in discord?
id love to help with TheTracker!

**Comment by Alvarito050506** [comment]
Thanks! I will send you a message.

Also, the 2 things you requested are done. You can update now!

**Comment by acidpancake** [comment]
![image](https://user-images.githubusercontent.com/57821130/82744802-bdb10c80-9dc0-11ea-9f38-dcec26f0f1c8.png) add me here

**Comment by acidpancake** [comment]
thanks!

**Comment by Alvarito050506** [comment]
xD

**Comment by acidpancake** [comment]
lol
![image](https://user-images.githubusercontent.com/57821130/82744827-ef29d800-9dc0-11ea-8c0c-b5ef151059fa.png)
